### ISSUE TITLE
实体链接

### ISSUE THREAD

**Issue by tangdai0228** [AIRobotZhang/STCKA#1]
您好，初次接触实体链接这个部分。看到您使用的是tagme，请问对于中文有什么好的实体链接可以使用吗。

**Comment by AIRobotZhang** [comment]
> 您好，初次接触实体链接这个部分。看到您使用的是tagme，请问对于中文有什么好的实体链接可以使用吗。

CN-DBpedia或者复旦大学有个组对其的改进版
