### ISSUE TITLE
复现效果

### ISSUE THREAD

**Issue by NovemberSun** [AIRobotZhang/STCKA#5]
您好，不知道您有没有用您的复现结果和论文中的结果准确率进行比较呢？

**Comment by AIRobotZhang** [comment]
> 您好，不知道您有没有用您的复现结果和论文中的结果准确率进行比较呢？

您好，我们并没有采用原文中的数据进行实验，并且没有采用与原文中一致的知识库，谢谢您的提问！

**Comment by NovemberSun** [comment]
请问您有没有用您的数据进行其他文本分类实验并与该方法结果进行比较呢，谢谢您的回答：）

**Comment by AIRobotZhang** [comment]
> 请问您有没有用您的数据进行其他文本分类实验并与该方法结果进行比较呢，谢谢您的回答：）

很抱歉，并没有与现有的模型进行定量比较，欢迎您report您的对比效果！

**Comment by NovemberSun** [comment]
![image](https://user-images.githubusercontent.com/32707117/92390435-6e170680-f14d-11ea-9813-0e5830f5c998.png)
您好，今天跑了您的代码和您的数据集tagmynews.tsv,在gpu上几分钟完成训练，这是我的结果，请问和您自己跑的时候结果一致吗，非常感谢您的开源！：）

**Comment by AIRobotZhang** [comment]
> ![image](https://user-images.githubusercontent.com/32707117/92390435-6e170680-f14d-11ea-9813-0e5830f5c998.png)
> 您好，今天跑了您的代码和您的数据集tagmynews.tsv,在gpu上几分钟完成训练，这是我的结果，请问和您自己跑的时候结果一致吗，非常感谢您的开源！：）

差不多，但是应该比原论文中的效果要差，本仓库中开源的代码与原论文中采用的文本Concept不同

**Comment by NovemberSun** [comment]
后续我计划用中文知识库进行一些实验，感谢您的开源
